ai-tweet-generator:
  streaming-data-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  ai-service: SpringAI-OpenAI
  scheduler-duration-sec: 120
  prompt: "Write a COMPLETE Twitter post about Java microservices using Spring and Kafka.

Rules:
- Must be exactly 2 sentences
- Each sentence must be complete
- Total 20–30 words
- Include at least 1 emoji
- End with a strong statement
- Do NOT stop early"
  keywords-placeholder: '{keywords}'
  open-ai:
      url: "https://api.openai.com/v1/chat/completions"
      api-key: ${OPENAI_API_KEY}
      content-type: "application/json"
      model: "gpt-4o-mini"
      max-completion-tokens: 150
      temperature: 1
      messages:
        - role: "user"
          content:
            -
              type: "text"
  google-gen-ai:
    apiKey: ${GOOGLE_API_KEY}
    modelName: "gemini-3-flash-preview"
#    max-output-tokens: 150
#    temperature: 1
#    candidate-count: 1
spring:
  ai:
    openai:
      #      api-key: ${OPENAI_API_KEY}
      api-key: ${DEEPSEEK_API_KEY}
      #      base-url: "https://api.openai.com"
      base-url: "https://api.deepseek.com"
      chat:
        options:
          #          model: "gpt-4o-mini"
          model: deepseek-chat
          temperature: 1
          maxTokens: 150
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:14b
          temperature: 1
          max-new-tokens: 150
server:
  port: 8089